export const CHANGE_BASE_VALUE = "CHANGE_BASE_VALUE"
export const CHANGE_CATEGORIES = "CHANGE_CATEGORIES"
export const CHANGE_UNIT_ID_INPUT = "CHANGE_UNIT_ID_INPUT"
export const CHANGE_UNIT_ID_RESULT = "CHANGE_UNIT_ID_RESULT"